name: '1.0.2.$(BuildID)'
pool:
  vmImage: 'vs2017-win2016'
  
trigger:
  branches:
    include: [ 'master' ]

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Build'
  workingDirectory: '$(Build.SourcesDirectory)/ProcessMyMedia/'
- script: dotnet test --configuration $(buildConfiguration) --logger:trx
  displayName: 'Test'
  workingDirectory: '$(Build.SourcesDirectory)/ProcessMyMedia.Tests/'
- task: PublishTestResults@2
  displayName: 'Publish Test Result'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    buildConfiguration: $(buildConfiguration)
    publishRunAttachments: true
- script: dotnet pack /p:Version=$(Build.BuildNumber) --configuration $(buildConfiguration)
  displayName: 'Pack'
  workingDirectory: '$(Build.SourcesDirectory)/ProcessMyMedia/'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/ProcessMyMedia/bin/$(buildConfiguration)/'
    artifactName: 'drop'