name: '1.0.1.$(BuildID)'
pool:
  vmImage: 'vs2017-win2016'
  
trigger:
  branches:
    include: [ 'master' ]

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build '$(Build.SourcesDirectory)/ProcessMyMedia/ProcessMyMedia.csproj' --configuration $(buildConfiguration) --output 'out/bin'
  displayName: 'Build'
- script: dotnet test '$(Build.SourcesDirectory)/ProcessMyMedia.Tests/ProcessMyMedia.Tests.csproj' --configuration $(buildConfiguration) --logger:trx
  displayName: 'Test'
- task: PublishTestResults@2
  displayName: 'Publish Test Result'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    buildConfiguration: $(buildConfiguration)
    publishRunAttachments: true
- script: dotnet pack '$(Build.SourcesDirectory)/ProcessMyMedia/ProcessMyMedia.csproj' /p:Version=$(Build.BuildNumber) --configuration $(buildConfiguration) --output 'out/package'
  displayName: 'Pack'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/ProcessMyMedia/out/bin/'
    artifactName: 'bin'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Package Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/ProcessMyMedia/out/package/'
    artifactName: 'package'
