pool:
  vmImage: 'Ubuntu 16.04'
  
trigger:
  branches:
    include: [ 'master' ]

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build 'ProcessMyMedia/ProcessMyMedia.csproj' --configuration $(buildConfiguration) --output 'out/bin'
  displayName: 'Build'
- script: dotnet test 'ProcessMyMedia.Tests/ProcessMyMedia.Tests.csproj' --configuration $(buildConfiguration) --logger:trx
  displayName: 'Test'
- task: PublishTestResults@2
  displayName: 'Publish Test Result'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    buildConfiguration: $(buildConfiguration)
    publishRunAttachments: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: 'ProcessMyMedia/out/bin/'
    artifactName: 'bin'
